allowBuilds:
  '@clerk/shared': true
  '@tailwindcss/oxide': true
  esbuild: true
  sharp: true

minimumReleaseAgeExclude:
  - '@clack/core@1.4.0'
  - '@clack/prompts@1.5.0'
  - '@rollup/pluginutils@5.4.0'
  - tinyexec@1.2.3
